evidence_requirements:
- evidence_type: metric
  code_template: |
    import os

    import requests
    from azure.ai.evaluation import FluencyEvaluator, evaluate
    from azure.ai.projects import AIProjectClient
    from azure.identity import DefaultAzureCredential

    ##################################
    # STEPS
    # 0. This script assumes you have already installed the Azure AI Evaluation SDK, the Azure AI Projects SDK, and the Azure Identity SDK.
    #    Prior to running the script you should have created a project in Azure AI Foundry and have logged in with the Azure CLI.
    #
    # 1. Ensure you Credo AI API key is set in your environment OR manually set it in the script
    #
    # 2. Set up the Azure configurations to use the project and model you want to use for evaluation
    #
    # 3. Fill in the value for your Credo AI tenant (the name of your organization that you use to log in to the Credo AI Platform)
    #
    # 4. Run the script without editing below line 88
    ##################################


    ####################################################################
    # Credo AI Platform Information
    ####################################################################

    # API Token, which can be created on the Credo AI Platform
    # Link: https://app.credo.ai/my-settings/tokens/
    # We recommend storing this as an environment variable as CREDOAI_API_KEY
    API_TOKEN = os.getenv("CREDOAI_API_KEY", "YOUR_API_KEY")

    TENANT = os.getenv("CREDOAI_TENANT", "mytenant")  ### FILL IN TENANT -- this is the name of your organization that you use to log in to the Credo AI Platform


    ####################################################################
    # Azure AI Foundry Information
    ####################################################################
    # Foundry evaluators expect the user to specify the "judge" model that will be used to evaluate the system's performance,
    # and *data* generated by the system being evaluated.
    # The evaluation does not directly invoke the system being evaluated.

    # Create an Azure AI Client from a connection string. Available on project overview page on Azure AI project UI.

    # Connection string is available on the project overview page on Azure AI project UI
    project_client = AIProjectClient(
        endpoint=os.getenv("AZURE_CONNECTION_STRING", "Your connection string"),
        credential=DefaultAzureCredential(),
    )

    # Set up the model config for the evaluator
    judge_model_config = {
        "azure_endpoint": os.getenv("AZURE_ENDPOINT_URI", "Your Azure OpenAI endpoint"),  # available on the models & endpoints page
        "api_key": os.getenv("AZURE_API_KEY", "Your Azure project API key"),
        "azure_deployment": os.getenv("AZURE_JUDGE_MODEL_DEPLOYMENT_NAME", "Deployment name"),  # the name of the model deployment (e.g. gpt-4o-mini)
        "api_version": os.getenv("AZURE_API_VERSION", "API version"),  # the API version (e.g. 2024-08-01-preview)
    }


    # Set up the Azure AI project config
    # All three of these values are available by clicking on the "Project" dropdown on the top right of the Azure AI Foundry UI
    azure_ai_project = {
        "subscription_id": os.getenv("AZURE_SUBSCRIPTION_ID", "Your subscription ID"),
        "resource_group_name": os.getenv("AZURE_RESOURCE_GROUP_NAME", "Your resource group name"),
        "project_name": os.getenv("AZURE_PROJECT_NAME", "Your project name"),
    }

    # Specify the file path to the data you want to evaluate
    # This should be a JSONL file with the following columns: query, context, response, ground_truth
    # (Requirements vary by evaluator)
    data_file_path = os.getenv("EVALUATION_DATA_PATH", "Path to evaluation data jsonl file")

    # The data can alternatively be loaded from an Azure-hosted blob storage container. See https://learn.microsoft.com/en-au/azure/ai-studio/how-to/develop/evaluate-sdk for guidance.

    # Run the evaluation
    # This function will return a dictionary with the evaluation metrics AND it will push the evaluation results to the Azure AI Foundry project
    evaluation = evaluate(
        data=data_file_path,
        evaluators={
            "fluency": FluencyEvaluator(model_config=judge_model_config)
        },
        evaluator_config={
            "fluency": {
                "column_mapping": {
                    "response": "${data.response}",  # Required field
                }
            }
        },
        azure_ai_project=azure_ai_project,
    )

    ####################################################################
    # Code below this line should not need to be edited
    ####################################################################

    eval_score = evaluation["metrics"]["fluency.gpt_fluency"]

    # ************************
    # Credo AI Evidence Bundling Class
    # *************************

    # This classes are used to structure the evidence in a more readable way.
    # Refer to the class documentation for what is expected for each evidence type.


    class MetricEvidence:
        """
        MetricEvidence stores a metric value and optional confidence interval. It's used for packaging evidence to upload to the Credo AI Platform.

        Args:
        - value: metric value.
        - confidence_interval: optional integer defining the confidence interval (e.g., 99 for 99% CI).
        - confidence_interval_range: optional [lower bound, upper bound] of the metric.
        """

        def __init__(self, value, confidence_interval=None, confidence_interval_range=None):
            self.value = value
            self.confidence_interval = confidence_interval
            self.confidence_interval_range = (
                confidence_interval_range
                if confidence_interval_range is not None
                else [None, None]
            )


    # ********************************
    # Set Up Evidence - FILL IN VALUES
    # ********************************

    # The EVIDENCE_DICTIONARY structures the required evidence to upload to the Credo AI Platform
    # The appropriate value for the `eval_score` is pre-filled above and should not need to be edited.


    EVIDENCE_DICTIONARY = {
        # Evaluate the system's factuality on a representative dataset
        "${EVIDENCE_REQUIREMENT.KEY}": {
            "requirement_key": "${EVIDENCE_REQUIREMENT.KEY}",
            "data": MetricEvidence(value=eval_score).__dict__,
        },
    }

    # ************************
    # Upload Evidence
    # ************************

    # Code to upload evidence to the Credo Platform via API.
    # No code changes are required here.

    API_URL = "https://api.credo.ai"
    url = "https://api.credo.ai/api/v2/" + TENANT + "/use_cases/${USE_CASE.ID}/controls/${CONTROL.ID}/evidences"

    # get headers
    headers = {"content-type": "application/json", "charset": "utf-8"}
    exchange_body = {"api_token": API_TOKEN, "tenant": TENANT}
    exchange_url = os.path.join(API_URL, "auth", "exchange")
    response = requests.post(exchange_url, json=exchange_body, headers=headers)
    access_token = response.json()["access_token"]
    headers = {
        "Authorization": f"Bearer {access_token}",
        "content-type": "application/json",
        "charset": "utf-8",
    }

    # Evidence for each requirement is uploaded to the Credo AI Platform
    # with a separate API call.
    for requirement, data in EVIDENCE_DICTIONARY.items():
        requests.post(url, json=data, headers=headers)
  description: |
    # Running the Evaluator

    Copy the skeleton code example below and fill in the relevant information for your Azure project, judge model, dataset, and API credentials. Ensure that your Credo AI API key is also provided. Credo AI API keys can be obtained in the Settings -> Tokens tab of the Credo AI platform.

    Once this information is provided, running the code will automatically run the evaluation and push it to the Credo AI platform.

    # Interpretation

    ## Fluency Evaluator

    `FluencyEvaluator` measures the effectiveness and clarity of written communication, focusing on grammatical accuracy, vocabulary range, sentence complexity, coherence, and overall readability. It assesses how smoothly ideas are conveyed and how easily the reader can understand the text.

    ## Outputs

    The evaluator outputs a numerical score on a Likert scale (integer 1 to 5) for a given sample. A higher score indicates better fluency. When a data set is evaluated, the average score is reported. The evaluator passing score cutoff is defined by Microsoft Azure's documentation as 3.
  label:
    key: 25ffd515
  question: Run the Microsoft Azure AI Evaluation SDK Fluency evaluator on data generated by the AI system relevant to this use case using the provided skeleton code.
  mathematical_bound:
    lower: 1
    upper: 5
  governance_bounds:
  - hex_color: "#ff0000"
    lower: 1
    upper: 3
    name: Fail
  - hex_color: "#00ff00"
    lower: 3
    upper: 5
    name: Pass

info:
  author: Credo AI
  control_type: model
  description: '[MSFT-FLUENCY] Establish and apply performance testing and validation framework'
  implementation_guidance: |
    # General Guidance

    The provided skeleton code illustrates how to run the Fluency Evaluator on an AI system and, using the requests library, send the results to the Credo AI platform such that they are associated with this control.

    At the top of the skeleton code, you will see a section for "Configuration". This is where you will need to add your Azure AI Evaluation SDK credentials, specify the model you want to evaluate, and specify the input data you want to evaluate.

    Do not modify the code below the "Configuration" section, as this could cause the submission of evidence to the Credo AI platform to fail.
  long_description: |
    ## Control Description

    This control is a companion to the CREDOAI-012 control "Establish and apply performance testing and validation framework". This control is a specific instantiation to prompt business users to run the Fluency Evaluator on their AI system and should be used as part of the overall process of evaluating the performance of the AI system.

    ### Associated Risk Scenarios:
    These risk scenarios are mitigated by this control.

    - Lack of adequate capabilities
    - Oversight and evaluation challenges
    - Integration challenges with existing systems

    ### Keywords
    benchmarking, evaluation sets, few-shot testing, zero-shot testing
key: MSFT-FLUENCY
metadata:
  model_types:
  - traditional_ml
  - genai
risk_type_ids:
- Se5Zh6HvBtxsCayoB8uLxW
- c7WEndUDAHt25qsV4R5Ut8
version: 2
